### PR TITLE
Update markup of black square dot subtitles in Appendix 1

### PR DESCRIPTION
**Pull request by manuel489**
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/136*

This PR contains the markup updates of black square subtitles, as indicated in https://github.com/metanorma/bipm-si-brochure/issues/136.

Thanks!

### CODE REVIEW

**Comment by manuel489** [comment]
@Intelligent2013,
The issue that see in generated PDFs is that these titles are completely boldfaced despite the markup.

Example:
```adoc
...
[[cgpm13th1967r1]]
=== {blank}

[.variant-title,type=quoted]
*SI unit of time (second)* (CR, 103 and _Metrologia_, 1968, *4*, 43) (((second (stem:["unitsml(s)"]))))
...
```

Renders:
issue1-generated


Instead of (original):
issue1-original

That's the only issue I noticed.
(When you solved it, can you upload the generated PDF for me to review? Thanks!)

**Comment by Intelligent2013** [comment]
> The issue that see in generated PDFs is that these titles are completely boldfaced despite the markup.

@manuel489  issue fixed (commit https://github.com/metanorma/mn-native-pdf/commit/ce7fa4eb713490df301cd7a20d8adf1d9e79fec1):
image


Resulted PDF:
[collection.presentation.zip](https://github.com/metanorma/bipm-si-brochure/files/7192711/collection.presentation.zip)

**Comment by manuel489** [comment]
@Intelligent2013, why `stem` expressions aren't rendering?

Markup sample:
```adoc
*déclare que* l’étalon à employer est la transition entre les niveaux hyperfins((("atome de césium, niveaux hyperfins")))
stem:[ii(F) = 4], stem:[ii(M) = 0] et stem:[ii(F) = 3], stem:[ii(M) = 0] de l’état fondamental stem:[text()^2"S"_(1//2)]
de l’atome de césium((("atome de césium, niveaux hyperfins"))) 133 non perturbé par des champs
extérieurs, et que la valeur stem:[9192631770] hertz(((hertz (stem:["unitsml(Hz)"]))))
est assignée à la fréquence de cette transition.
```

Generated:
issue2-generated


Original:
issue2-original

**Comment by Intelligent2013** [comment]
> why some `stem` expressions aren't rendering?

@manuel489 issue fixed.
Resulted PDF: [collection.presentation.zip](https://github.com/metanorma/bipm-si-brochure/files/7196003/collection.presentation.zip)

**Comment by manuel489** [comment]
Thanks @Intelligent2013!
Problem solved. Merging.

**Pull request merged**
