### PR TITLE
Correct French text formatting issues

### PR DESCRIPTION
**Pull request by manuel489**
*As requested in https://github.com/metanorma/bipm-si-brochure/issues/80*

Actions taken:

* Removed space in front of commas (in both English and French versions).
* Inserted non-breakable space in colons and semi-colons in French version. 
(These were the only double punctuation marks found.)

Thanks

### CODE REVIEW

**Comment by ronaldtse** [comment]
@manuel489 questions
- why are we sometimes using `&nbsp;` and sometimes `{nbsp}`?
- why are we using nbsp instead of a normal space for French?

**Comment by manuel489** [comment]
@ronaldtse, answering your questions:

> why are we sometimes using &nbsp; and sometimes {nbsp}?

I use `{nbsp}` to avoid markup confusion with the semi-colons.
For example,  I find it visible confusing to write `&nbsp;;`; plus, my syntax highlighting does weird things 😓. 
So I put  `{nbsp};` instead which does the same thing.
(Maybe with the colons is not that big deal.)

> why are we using nbsp instead of a normal space for French?

Well, this is necessary to avoid line-break separation.
For example:
````
Random text
:
````

(Something similar happened with `« »` quotation marks.)

**Comment by ronaldtse** [comment]
Then let's only use {nbsp} instead of `&nbsp;` everywhere?

> Well, this is necessary in order to avoid line-break separation.

I see, okay.

**Comment by manuel489** [comment]
> Then let's only use {nbsp} instead of &nbsp; everywhere?

Ok

**Comment by manuel489** [comment]
Done

**Pull request merged**
