### PR TITLE
metanorma/metanorma-build-scripts#71 Update workflow to include shared one

### PR DESCRIPTION
**Pull request by CAMOBAP**
As title. 

 _Generated by Cimas_.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP conflicts in this one.

**Comment by ronaldtse** [comment]
@CAMOBAP can you help merge this? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse sure all failed repos are in my list

**Comment by ronaldtse** [comment]
@CAMOBAP we want to have the site publish workflow for this.

**Comment by CAMOBAP** [comment]
> @CAMOBAP we want to have the site publish workflow for this.

Right, but we already do this as part of docker workflow, here https://github.com/metanorma/metanorma-build-scripts/blob/main/.github/workflows/sample-docker.yml#L69-L92

Should we do anything additionally?

**Pull request merged**
