### PR TITLE
Apply new markup in ToC Appendix1

### PR DESCRIPTION
**Pull request by manuel489**
*In relation to https://github.com/metanorma/metanorma-standoc/issues/515*

### CODE REVIEW

**Comment by Intelligent2013** [comment]
Line 204:
```adoc
* <<cgpm23rd2007r12"23rd CGPM, 2007:pass:[<tab/>]on the possible redefinition of certain base units(((base unit(s)))) of the International System of Units (SI)">>
```

comma missed before `23rd CGPM`.
@manuel489 I've generated XML and need to change xslt for PDF rendering. Then I'll attach resulted PDF for checking.

**Comment by manuel489** [comment]
Thanks @Intelligent2013, fixed.

**Comment by Intelligent2013** [comment]
1. ToC section title and index should be placed in the one line.
Current adoc:
```adoc
==== Mass
(((mass)))
```
Generated xml contains `title` and `p`:
```xml
<title depth="4">1.1.2.2.<tab/>Mass</title>
<p id="_acc998a8-2438-43c0-b4e5-e57d3ca7167a"><bookmark id="_99f01d3c-f3e7-4121-80f1-819470828076"/></p>
```
In pdf it will be displayed with space (empty paragraph) after title:
Example displaying of subsection titles:
image


Correct variant:
```adoc
==== Mass (((mass)))
```

Note: `==== Length (((length)))` encoded ok.

2. I don't sure that markup is correct:
```adoc
* <<cgpm9th1948r6,"9th CGPM, 1948:pass:[<tab/>]decision to establish the SI">>
```
In the generated XML there is a quote before `9th` and at the end, and there is `:` after `1948`:
```xml
<xref target="cgpm9th1948r6">1.6.3<tab/>&#8220;9th CGPM, 1948:<tab/>decision to establish the SI&#8221;</xref>
```

3. I think that `[variant-title,type=toc]` should be placed in main text, not in ToC:
```adoc
* <<cipm1956r3>>
[variant-title,type=toc]
CIPM, 1956:pass:[<tab/>]decision to adopt the name "Système International d'Unités"
```
Resulted XML:
```xml
<xref target="cipm1956r3">1.8.2<tab/>Syst&#232;me International d&#8217;Unit&#233;s (PV, 25, 83)</xref>
CIPM, 1956:<tab/>decision to adopt the name &#8220;Syst&#232;me International d&#8217;Unit&#233;s&#8221;
```

**Comment by Intelligent2013** [comment]
> there is `:` after 1948

it's ok, ignore this remark.

**Comment by opoudjis** [comment]
> I think that [variant-title,type=toc] should be placed in main text, not in ToC:

````
* <<cipm1956r3>>
[variant-title,type=toc]
CIPM, 1956:pass:[<tab/>]decision to adopt the name "Système International d'Unités"
````

That's correct, it needs to appear after the `[[cipm1956]]` title.

**Comment by manuel489** [comment]
@Intelligent2013, fixes applied. Thanks!

**Comment by Intelligent2013** [comment]
1. Correct markup for `variant-title`
```adoc
[[cipm1956r3]]
=== Système International d'Unités (PV, 25, 83)
[.variant-title,type=toc]
CIPM, 1956:pass:[<tab/>]decision to adopt the name "Système International d'Unités"
```
1.1 before `variant-title` should be dot
1.2. after `[.variant-title,type=toc]` should be placed ToC title.

2. No need to put quotas around reference text
```adoc
* <<cgpm9th1948r6,"9th CGPM, 1948:pass:[<tab/>]decision to establish the SI">>
```
Correct:
```adoc
* <<cgpm9th1948r6,9th CGPM, 1948:pass:[<tab/>]decision to establish the SI>>
```
3. It seems it would be better to put all ToC titles directly in `<<.., here>>`, because there are a few cases, when different titles are using for one references. For example, `cgpm10th1954r6`:
```adoc
* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]decision on the first six base units(((base unit(s))))>>
...
* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]metre adopted as a base unit(((base unit(s))))>>
...
* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]kilogram adopted as a base unit(((base unit(s))))>>
...
* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]second adopted as a base unit(((base unit(s))))>>
...
* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]ampere(((ampere (stem:["unitsml(A)"])))) adopted as a base unit(((base unit(s))))>>
...
* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]degree Kelvin adopted as a base unit(((base unit(s))))>>
...
* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]candela(((candela (stem:["unitsml(cd)"])))) adopted as a base unit(((base unit(s))))>>
```
and no need to use `variant-title` markup.

I've changed English adocs.

Resulted PDF:  [si-brochure-en.toc.presentation.pdf](https://github.com/metanorma/bipm-si-brochure/files/7188209/si-brochure-en.toc.presentation.pdf)

@manuel489 if English PDF is ok, could you make similar changes in adocs for French version? Thanks!

**Comment by manuel489** [comment]
@Intelligent2013, according the BIPM, the phrase "mise en pratique" should be italicized, always.

In the PDF you shared above none of the "mise en pratique" are in italics, even when the markup is correct:

cap1

**Comment by Intelligent2013** [comment]
@manuel489 thank you! Generated brochure PDF for checking:
[collection.presentation.zip](https://github.com/metanorma/bipm-si-brochure/files/7190475/collection.presentation.zip)

**Comment by Intelligent2013** [comment]
> In the PDF you shared above, none of the "mise en pratique" instances are in italics, even when the markup is correct:

Issue in the xslt fixed.

**Comment by manuel489** [comment]
Thanks @Intelligent2013,
In regard to the ToC of Appendix 1, I didn't find any issues in both versions, French and English.

**Comment by manuel489** [comment]
That been said, I did notice a little issue with the square bullet subtitles in Annex 1. In relation to this ticket: https://github.com/metanorma/bipm-si-brochure/issues/136
I understand that these square bullets should not be present since the corresponding markup is not applied in this PR, and yet, they are appearing. But I'd like to discuss about this in another PR in order to not mix things up.

So, maybe we can merge this changes first?

**Review by Intelligent2013 — APPROVED** [review]

**Comment by Intelligent2013** [comment]
> 
> 
> That been said, I did notice a little issue with the square bullet subtitles in Annex 1. In relation to this ticket: #136
> I understand that these square bullets should not be present since the corresponding markup is not applied in this PR, and yet, they are appearing. But I'd like to discuss about this in another PR in order to not mix things up.
> 
> So, maybe we can merge this changes first?

@manuel489 yes, please feel free to merge.

**Pull request merged**
