### PR TITLE
Add CR and PV references

### PR DESCRIPTION
**Pull request by anermina**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Let's merge this first since the encoding is correct. Thanks everyone!

**Comment by ronaldtse** [comment]
@Intelligent2013 the build seems to be failing here due to Noto. Do you have any idea?

e.g.
* https://github.com/metanorma/bipm-si-brochure/runs/6860162082?check_suite_focus=true

**Comment by Intelligent2013** [comment]
@ronaldtse  The message `WARNING: Font file '/home/runner/.metanorma/fonts/WorkSans-Thin.ttf' (font name 'Work Sans', font style 'normal', font weight '100') doesn't exist. Replaced by '/home/runner/.metanorma/fonts/NotoSans-Regular.ttf'.` means that the font `WorkSans` didn't installed, but it should be installed by metanorma-bipm:
```
      def fonts_manifest
        {
          "Arial" => nil,
          "Times New Roman" => nil,
          "Work Sans" => nil,
          "Work Sans Black" => nil,
          "Work Sans ExtraBold" => nil,
          "Work Sans ExtraLight" => nil,
          "Work Sans Light" => nil,
          "Work Sans Medium" => nil,
          "Work Sans SemiBold" => nil,
          "Work Sans Thin" => nil,
          "STIX Two Math" => nil,
          "Source Han Sans" => nil,
          "Source Han Sans Normal" => nil,
          "TeXGyreChorus" => nil,
        }
      end
```

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 for the investigation -- is this a bug @CAMOBAP

**Comment by ronaldtse** [comment]
> @ronaldtse Found. The command line for collection PDF doesn't contain the parameter `--font-manifest "/tmp/fontist_locations20220613-......yml"`:
> 
> ```
> java -Xss5m -Xmx2048m -jar /tmp/packed-mn-20220613-4193-al36ja/mn2pdf.jar --xml-file "collection/collection.presentation.xml" --xsl-file "/tmp/packed-mn-20220613-4193-al36ja/bipm.brochure.xsl" --pdf-file "collection/collection.pdf" --syntax-highlight  --split-by-language
> ```
> 
> therefore mn2pdf can't find WorkSans font installed by metanorma-bipm into the folder `.fontist`. But I don't understand why mn2pdf can't download the font WorkSans themself (the command line from macos is similar without font-manifest: `java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/packed-mn-20220613-92606-buuexs/mn2pdf.jar --xml-file "collection/collection.presentation.xml" --xsl-file "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/packed-mn-20220613-92606-buuexs/bipm.brochure.xsl" --pdf-file "collection/collection.pdf" --syntax-highlight --split-by-language`)
> 
> But for en- fr-versions everything is ok:
> 
> ```
> java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/packed-mn-20220613-92606-buuexs/mn2pdf.jar --xml-file "/Users/runner/work/bipm-si-brochure/bipm-si-brochure/collection/si-brochure-fr.presentation.xml" --xsl-file "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/packed-mn-20220613-92606-buuexs/bipm.brochure.xsl" --pdf-file "/Users/runner/work/bipm-si-brochure/bipm-si-brochure/collection/si-brochure-fr.pdf" --syntax-highlight  --font-manifest "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/fontist_locations20220613-92606-13ez1x5.yml"
> ```

I no longer see this issue, I can generate both English and French fine now.

**Comment by ronaldtse** [comment]
There are a few remaining problems, but I will merge this first.

English bibliography has jumping numbers:
Screenshot 2022-06-20 at 4 40 01 PM
 
French bibliography does not hide items that should be hidden:
Screenshot 2022-06-20 at 4 41 39 PM

English index showing "BROUILLON" instead of English watermark "DRAFT":
Screenshot 2022-06-20 at 4 41 19 PM

**Comment by ronaldtse** [comment]
Thank you everyone!

**Pull request merged**
