### PR TITLE
feat: simplify BIPM information references, fixes #212

### LINKED ISSUE #212: Update SI Brochure references to outcomes
In the SI Brochure, there are only a few references to outcomes (CR, PV, Recommendation/Resolutions) in the body (not in the resolutions).

As approved by Michael Stock of the BIPM, we will update these references:

2.3.1 “The Kelvin”:
Screen Shot 2023-02-07 at 2 55 30 PM

To: "adopted in CIPM Recommendation 5 (1989)"
https://www.bipm.org/en/committees/ci/cipm/78-1989/resolution-5

Table 4:
Screen Shot 2023-02-07 at 2 56 25 PM

To:
"See CIPM Recommendation 2 (2002) on the use of the sievert."
https://www.bipm.org/en/committees/ci/cipm/91-2002/resolution-2

Table 8:
Screen Shot 2023-02-07 at 2 56 49 PM

To:
"adopted in CIPM Resolution (1879)."
https://www.bipm.org/en/committees/ci/cipm/4-1879/resolution-

Table 8:
Screen Shot 2023-02-07 at 2 57 05 PM

To:
"adopted in CIPM Resolution (1879)."
https://www.bipm.org/en/committees/ci/cipm/4-1879/resolution-
 
To:
"adopted in CGPM Resolution 6 (1979)"
https://www.bipm.org/en/committees/cg/cgpm/16-1979/resolution-6

Table 8:
Screen Shot 2023-02-07 at 2 57 12 PM

To:
"adopted in CIPM Resolution (1879)."
https://www.bipm.org/en/committees/ci/cipm/4-1879/resolution-

5.2:
Screen Shot 2023-02-07 at 2 57 47 PM

To:
"adopted in CGPM Resolution 6 (1979)"
https://www.bipm.org/en/committees/cg/cgpm/16-1979/resolution-6

_Originally posted by @ronaldtse in https://github.com/metanorma/bipm-si-brochure/issues/193#issuecomment-1425261816_

### PR DESCRIPTION
**Pull request by ronaldtse**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by ronaldtse** [comment]
@manuelfuenmayor @anermina could you please help review this document one last time before we hand over to BIPM?

The particular points to look at are the meeting / decision / resolutions references of the CIPM and CGPM.

The worry is that the changes to the references caused the rendering to differ greatly (especially if the French reference output is no longer French but English).

There are not so many changes, so please use the diff as a guide on what has changed:
* https://github.com/metanorma/bipm-si-brochure/pull/213/files

Thanks!

* English [collection_en.pdf](https://github.com/metanorma/bipm-si-brochure/files/11264523/collection_en.pdf)
* French [collection_fr.pdf](https://github.com/metanorma/bipm-si-brochure/files/11264526/collection_fr.pdf)

**Comment by manuelfuenmayor** [comment]
Also, there is this case that I think could be consider a minor issue:

3. There is a horizontal misalignment in the Table of Annex 1, between the first column and the second:
    Generated French version:
    brochure-issue-3-fr

    On the English version, the misalignment occurs in a different manner -- there are random line breaks in the first column:
    Generated English version:
    brochure-issue-3-en

**Comment by manuelfuenmayor** [comment]
In regard to the references, I noticed practically no issue.
There is a difference in the presentation compared to the original document.

Generated:
refs-1-fr

Original:
refs-1-fr-original

But I assume that that is the expected result.

**Comment by manuelfuenmayor** [comment]
I have converted the comments from above in tickets:
https://github.com/metanorma/metanorma-standoc/issues/777,
https://github.com/metanorma/metanorma-bipm/issues/287,
https://github.com/metanorma/metanorma-bipm/issues/288.

**Comment by ronaldtse** [comment]
Thank you @manuelfuenmayor ! I've also posted the Plurimath ticket.

**Comment by ronaldtse** [comment]
This is blocked by:
* https://github.com/metanorma/metanorma-bipm/issues/293
* https://github.com/metanorma/metanorma-bipm/issues/292

**Comment by manuelfuenmayor** [comment]
I have found new issues that were not before at the beginning of this review.

**Comment by ronaldtse** [comment]
@manuelfuenmayor this means we need to have tests to ensure the PDF layout is correct. We can’t keep doing manual reviews of an automatically produced artifact. Ping @Intelligent2013

**Comment by Intelligent2013** [comment]
> @manuelfuenmayor this means we need to have tests to ensure the PDF layout is correct. We can’t keep doing manual reviews of an automatically produced artifact. Ping @Intelligent2013

@ronaldtse I don't figure out how to ensure the PDF layout programmatically. If we've checked and made sure once that generated PDF is identical to original PDF, then on the next iterations I propose to compare _previously_ generated PDF with new PDF in such manner (visually comparison):
- open two PDFs - old and new - in the Adobe Reader
- set the identical scale,
- switch between two documents by Ctrl+Tab (on Win platform)
- then next page by Page Down
- again switch between two documents to make sure that changes are acceptable

Or use the compare feature in the Adobe Acrobat (full version).

**Comment by ronaldtse** [comment]
Merged. Thank you all!

**Pull request merged**
